### ISSUE TITLE
guard-for-in

### ISSUE THREAD

**Issue by g-plane** [aladdin-add/eslint-plugin-autofix#28]
文档：https://eslint.org/docs/rules/guard-for-in

思路是给 BlockStatement 套一层包含 `Object.prototype.hasOwnProperty` 的 IfStatement。

**Comment by aladdin-add** [comment]
因为不知道for循环内的内容，修改后执行结果不确定。

**Comment by g-plane** [comment]
比如？

**Comment by aladdin-add** [comment]
对这种修改执行过程的fix，我们最好能够谨慎一些。😄 

很难列举一个实际的例子，构造一个：
```js
var foo = function(){console.log("hi!");};
var bar = Object.create(foo);

for(var fn in bar){ fn();}
```
原来的代码会输出 "hi"
修改后不会执行foo()，不会输出。
