### ISSUE TITLE
no-proto

### ISSUE THREAD

**Issue by g-plane** [aladdin-add/eslint-plugin-autofix#30]
文档：https://eslint.org/docs/rules/no-proto

将 `MemberExpression` 换成 `Object.getPrototypeOf` 的 `CallExpression`。

**Comment by aladdin-add** [comment]
我觉得可以。

unrelated: proto 虽然是非标准的方法，但它是pre-es6 环境下唯一的可用方法，可以作为 unsafe 的一条。
