### ISSUE TITLE
Enforce returning the `problem`

### ISSUE THREAD

**Issue by g-plane** [aladdin-add/eslint-plugin-autofix#4]
When I was implementing the "no-console" rule, I forgot write `return problem` at the first time. Should we take some measures to prevent this?

Possible solutions:
- Use TypeScript. We can specify the return type of the `mapReports`, then if we forget, the compiler will fail to compile.
- Create a custom rule. Use ESLint to check if there's a `ReturnStatement`.

**Comment by aladdin-add** [comment]
TypeScript, the first way, seems need more work to do -- I'm not sure some libs like `eslint-rule-composer` has a d.ts

I don't have a strong opinion, but slightly prefer a custom rule. thoughts?

**Comment by g-plane** [comment]
Yes `eslint-rule-composer` doesn't have `.d.ts` files, however we can create it for ourselves (or contributing to that repository directy).

Both two solutions have pros and cons.
Cons of using TypeScript: It may need some type assertions, for example, we may need `node as BlockStatement` sometimes.
Cons of using custom ESLint rule: We may need to locate the accurate AST node deeply.

I don't mind using any solutions.

**Comment by g-plane** [comment]
While whether using TypeScript or not, we still can add `.d.ts` files for better editor experience.
