### ISSUE TITLE
no-useless-catch

### ISSUE THREAD

**Issue by golopot** [aladdin-add/eslint-plugin-autofix#40]
Autofix for `no-useless-catch` is is simpler in the case when there is no variable declaration in try block. Otherwise the fixer needs to inspect variable names in the scope to prevent variable name collision. 

```js
// Not fixable in this case.

try {
  const foo = await query(sql, parameters)
  return foo
} catch (err) {
  throw err
}

const foo = ...
```

Maybe this autofix could exists in eslint core?

**Comment by g-plane** [comment]
I'm not sure, but I don't think the ESLint team will intend to provide autofix for this rule.

**Comment by aladdin-add** [comment]
@golopot sounds reasonable! PRs are welcome. 😄
