### ISSUE TITLE
Auto fixing produces wrong syntax.

### ISSUE THREAD

**Issue by g-plane** [aladdin-add/eslint-plugin-autofix#44]
I noticed is that `autofix/no-unused-vars` doesn't work well with object destructuring.

before autofix
```
const { name, email } = this.props // "name" is unused
```

after autofix
```
const { , email } = this.props
```

coma is left

With unused imports everything works great.

_Originally posted by @serhiipalash in https://github.com/aladdin-add/eslint-plugin-autofix/issues/33#issuecomment-500158744_

**Comment by aladdin-add** [comment]
it can be found by a fuzzer, just like in the eslint repo.

I like it can be pulbished(not in eslint), to benifit plugin devs. ( I've been thinking aobut it for a while 😄 )
